//
//  ShaprFile.swift
//  Shaper3DImport
//
//  Created by Aldrich Co on 7/11/20.
//  Copyright © 2020 Aldrich Co. All rights reserved.
//

import Foundation
import CoreData
import UIKit
import Shapr3DFileConverter


extension ShaprFile {
	
	convenience init(fileEntity: Base3DFormat) {
		
		// note that with NSManagedObjects being autogenerated, some properties
		// that were marked non-optional still were generated to have optional
		// designation.
		let thumbData = fileEntity.imageThumbnail

		let imageData = fileEntity.imageFull
		
		let formatsArray = fileEntity.derivedFormats?.allObjects as? [Derived3DFormat]
		
		let derivedFormats: [DerivedFileFormat] = formatsArray?.compactMap { file in
			// !! improve fileExtension loading.
			
			DerivedFileFormat(id: file.id ?? UUID(),
							  size: file.size,
							  created: file.created ?? Date(),
							  fileExtension: ShaprOutputFormat(rawValue: file.fileExtension!)!,
							  data: file.data,
							  convertProgress: CGFloat(file.convertProgress))
		} ?? []
		
		self.init(id: fileEntity.id ?? UUID(),
				  filename: fileEntity.filename ?? "",
				  size: fileEntity.size,
				  created: fileEntity.created ?? Date(),
				  image: imageData?.scaledImage,
				  thumbnail: thumbData?.scaledImage,
				  data: fileEntity.data,
				  derivedFormats: derivedFormats)
	}
	
	// not used yet
	func toEntity(in context: NSManagedObjectContext) -> Base3DFormat {
		
		let file = Base3DFormat(context: context)
		
		file.filename = self.filename
		file.size = self.size
		file.imageThumbnail = self.thumbnail?.pngData()
		file.imageFull = self.image?.pngData()
		
		let formats: [Derived3DFormat] = derivedFormats.map { (derivedFormat: DerivedFileFormat) in
			let format = Derived3DFormat(context: context)
			format.base = file
			format.convertProgress = Float(derivedFormat.convertProgress)
			format.created = derivedFormat.created
			format.fileExtension = derivedFormat.fileExtension.rawValue
			format.size = derivedFormat.size
			return format
		}
		
		file.derivedFormats = NSSet(array: formats)
		
		file.created = self.created
		return file
	}
}
